spring.application.name=keycloak-engine

# Configurações para conexão com o Docker
keycloak.server-url=http://localhost:8080
keycloak.realm=master
keycloak.username=admin
keycloak.password=admin
keycloak.client-id=admin-cli

# Porta da nossa API (para não conflitar com o Keycloak que está na 8080)
server.port=8081
